name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Tauri App
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache-dependency-path: web/package-lock.json
          cache: 'npm'

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: web/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: NPM install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          cd web
          npm install

      - name: Build web
        run: |
          cd web
          npm run build

      - name: Cache Rust
        id: cache-rust
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('**/rust-toolchain') }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Setup Rust
        if: steps.cache-rust.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@1.82.0

      - name: Setup Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: tauri-build
      #     path: target/release/bundle/

  release:
    name: Release
    needs: build
    runs-on: windows-latest

    steps:
      - name: Artifacts
        uses: actions/download-artifact@v3
        with:
          name: tauri-build

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            src-tauri/target/release/bundle/**/*.*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          releaseName: Release ${{ github.ref_name }}
